basic.showIcon(IconNames.Surprised)
basic.forever(function () {
    SuperBit.Servo3(SuperBit.enServo.S1, SuperBit.enPos.forward, 90)
    SuperBit.Servo3(SuperBit.enServo.S2, SuperBit.enPos.forward, 90)
    SuperBit.Servo3(SuperBit.enServo.S3, SuperBit.enPos.forward, 90)
    SuperBit.Servo3(SuperBit.enServo.S4, SuperBit.enPos.forward, 90)
    basic.pause(1000)
    SuperBit.Servo(SuperBit.enServo.S5, 0)
    SuperBit.Servo(SuperBit.enServo.S6, 0)
    SuperBit.Servo(SuperBit.enServo.S7, 0)
    SuperBit.Servo(SuperBit.enServo.S8, 0)
    basic.pause(1000)
    SuperBit.Servo(SuperBit.enServo.S5, 180)
    SuperBit.Servo(SuperBit.enServo.S6, 180)
    SuperBit.Servo(SuperBit.enServo.S7, 180)
    SuperBit.Servo(SuperBit.enServo.S8, 180)
})
